### ISSUE TITLE
Console Error / Quests

### ISSUE THREAD

**Issue by Strahilchu** [Ironic8b498/Autorank#12]
Getting this error in console every time a player logs in, I'm using the recommended Quests plugin (set up goals for players) and followed instructions, IT WORKS BUT there is always this error.

Error in Console:
[10:31:40 WARN]: [Autorank] Plugin Autorank v5.2.1 generated an exception while executing task 781883
java.lang.NullPointerException: Cannot invoke "com.leonardobishop.quests.common.player.QPlayer.getQuestProgressFile()" because "playerData" is null
        at me.armar.plugins.utils.pluginlibrary.hooks.QuestsAlternative.getNumberOfCompletedQuests(QuestsAlternative.java:45) ~[Autorank-5.2.1.jar:?]
        at me.armar.plugins.autorank.hooks.quests.QuestsAlternative.getNumberOfCompletedQuests(QuestsAlternative.java:17) ~[Autorank-5.2.1.jar:?]
        at me.armar.plugins.autorank.pathbuilder.requirement.QuestsCompletedQuestsRequirement.meetsRequirement(QuestsCompletedQuestsRequirement.java:25) ~[Autorank-5.2.1.jar:?]
        at me.armar.plugins.autorank.pathbuilder.requirement.AbstractRequirement.isMet(AbstractRequirement.java:109) ~[Autorank-5.2.1.jar:?]
        at me.armar.plugins.autorank.pathbuilder.holders.CompositeRequirement.meetsRequirement(CompositeRequirement.java:179) ~[Autorank-5.2.1.jar:?]
        at me.armar.plugins.autorank.pathbuilder.Path.meetsAllRequirements(Path.java:180) ~[Autorank-5.2.1.jar:?]
        at me.armar.plugins.autorank.pathbuilder.Path.checkPathProgress(Path.java:75) ~[Autorank-5.2.1.jar:?]
        at me.armar.plugins.autorank.playerchecker.PlayerChecker.checkPlayer(PlayerChecker.java:36) ~[Autorank-5.2.1.jar:?]
        at me.armar.plugins.autorank.listeners.PlayerJoinListener.lambda$onPlayerJoin$0(PlayerJoinListener.java:56) ~[Autorank-5.2.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1970]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.4.jar:git-Purpur-1970]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Relevant config:
    quests completed quests:
      value: 50

**Comment by Strahilchu** [comment]
Quests v3.13.3
