### ISSUE TITLE
Error with Quests

### ISSUE THREAD

**Issue by Strahilchu** [Ironic8b498/Autorank#8]
[03:58:43 WARN]: [Autorank] Plugin Autorank v5.2.0 generated an exception while executing task 441957
java.lang.NullPointerException: Cannot invoke "com.leonardobishop.quests.common.player.QPlayer.getQuestProgressFile()" because "playerData" is null
        at me.armar.plugins.utils.pluginlibrary.hooks.QuestsAlternative.getNumberOfCompletedQuests(QuestsAlternative.java:45) ~[Autorank-5.2.0.jar:?]
        at me.armar.plugins.autorank.hooks.quests.QuestsAlternative.getNumberOfCompletedQuests(QuestsAlternative.java:17) ~[Autorank-5.2.0.jar:?]
        at me.armar.plugins.autorank.pathbuilder.requirement.QuestsCompletedQuestsRequirement.meetsRequirement(QuestsCompletedQuestsRequirement.java:25) ~[Autorank-5.2.0.jar:?]
        at me.armar.plugins.autorank.pathbuilder.requirement.AbstractRequirement.isMet(AbstractRequirement.java:109) ~[Autorank-5.2.0.jar:?]
        at me.armar.plugins.autorank.pathbuilder.holders.CompositeRequirement.meetsRequirement(CompositeRequirement.java:179) ~[Autorank-5.2.0.jar:?]
        at me.armar.plugins.autorank.pathbuilder.Path.meetsAllRequirements(Path.java:180) ~[Autorank-5.2.0.jar:?]
        at me.armar.plugins.autorank.pathbuilder.Path.checkPathProgress(Path.java:75) ~[Autorank-5.2.0.jar:?]
        at me.armar.plugins.autorank.playerchecker.PlayerChecker.checkPlayer(PlayerChecker.java:36) ~[Autorank-5.2.0.jar:?]
        at me.armar.plugins.autorank.listeners.PlayerJoinListener.lambda$onPlayerJoin$0(PlayerJoinListener.java:43) ~[Autorank-5.2.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[petal-1.19.2.jar:git-petal-"cc69154"]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[petal-1.19.2.jar:git-petal-"cc69154"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[petal-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Ironic8b498** [comment]
if you're still getting this error, what version of Quest?

**Comment by Strahilchu** [comment]
> if you're still getting this error, what version of Quest?

v3.13.3
