### ISSUE TITLE
ar check <nickname> use in the console

### ISSUE THREAD

**Issue by rkfsociety** [Ironic8b498/Autorank#9]
[23:59:29 WARN]: java.util.concurrent.ExecutionException: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @7aec35a)
[23:59:29 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[23:59:29 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[23:59:29 WARN]:        at Autorank.jar//me.armar.plugins.autorank.commands.manager.AutorankCommand.lambda$runCommandTask$1(AutorankCommand.java:56)
[23:59:29 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[23:59:29 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:59:29 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:59:29 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:59:29 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:59:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[23:59:29 WARN]: Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @7aec35a)
[23:59:29 WARN]:        at Autorank.jar//me.armar.plugins.autorank.util.AutorankTools.sendDeserialize(AutorankTools.java:254)
[23:59:29 WARN]:        at Autorank.jar//me.armar.plugins.autorank.commands.CheckCommand.lambda$onCommand$1(CheckCommand.java:204)
[23:59:29 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[23:59:29 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[23:59:29 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
[23:59:29 WARN]:        ... 1 more

**Comment by rkfsociety** [comment]
no option to display information in the console? or is there something wrong with me?
